### ISSUE TITLE
identificare un possibile ranking per le persone famose sulla falsariga di Skiena con who's bigger

### ISSUE THREAD

**Issue by NNazem** [TheNoobRoxas/bigData#5]
Attualmente ho raccolto un po' di dati salvati nel file csv al link che trovate su colab. Sono riuscito a trovare le visualizzazioni degli ultimi 60 giorni, lunghezza della pagina, link interni ed esterni e numero di edit.

**Comment by NNazem** [comment]
Inoltre modificando leggermente lo script del prof abbiamo anche il PageRank delle pagine wikipedia

**Comment by semroncoroni02** [comment]
Cosa intendi con "identificare un possibile ranking"?
Tipo dare "pesi" differenti per determinati aspetti oppure tenere tutto con lo stesso peso?

Inoltre pensavo che la "quantità di risultati" trovati attraverso Google possa essere un altro bel dato per il calcolo no?
![image](https://user-images.githubusercontent.com/129330816/229310044-dd8e78f2-0b1f-429b-b1ef-f6027783a076.png)
(Già aggiunto al csv questo aspetto)

**Comment by semroncoroni02** [comment]
![image](https://user-images.githubusercontent.com/129330816/229310044-dd8e78f2-0b1f-429b-b1ef-f6027783a076.png)
Credo che la "quantità di risultati" trovati attraverso Google possa essere un altro bel dato per il calcolo no?

**Comment by NNazem** [comment]
In entrambi casi andrebbe bene

**Comment by semroncoroni02** [comment]
Era per capire se avessi capito la domanda...
Comune io darei pesi differenti per ogni categoria.
Tipo le ricerche negli ultimi 60 giorni potrebbero valere meno del numero di citazioni su wikipedia diciamo.
Stessa cosa per quello che ho aggiunto io, perchè cercando ad esempio "romolo" uscivano risultati non strettamente pertinenti a quello che ci interessava... venivano fuori pizzerie e cose varie... quindi credo sia tra le voci che devono valere bene.
Non so se è chiaro

**Comment by NNazem** [comment]
Sam non è che ogni risposta che ti do è per offenderti o per criticarti Ahahahaha, ho semplicemente detto in entrambi i casi andrebbe bene, l'importante è trovare il ranking migliore: se questo poi sia con o senza pesi lo capiremo solo con qualche test. Il numero di citazioni su wikipedia dovrebbe essere riferimenti ai link che ho messo, poi se intendi proprio citazioni senza link (che dubito vi siano, ma non ne sono sicuro) allora non so. Per le visualizzazioni dipende, per l'appunto Romolo ha tante citazioni ma poche visualizzazioni, il problema è che wikipedia non fornisce visualizzazioni totali ma soltanto negli ultimi 60 giorni

**Comment by NNazem** [comment]
La situa è difficile

**Comment by semroncoroni02** [comment]
Nono, come citazioni intendevo il riferimento ai link che hai già fatto tu.
Non saprei, secondo me ognuno potrebbe mettere giù una scaletta in ordine di importanza e un commento sul perché secondo lui è quello l'orine più corretto per importanza.
Così facendo secondo me riusciamo a tirare fuori una scaletta generale , per quanto riguarda il commento invece credo possa essere utile sia a noi ma sopratutto al prof che così capisce che dietro c'è stato un determinato lavoro e non a abbiamo messo pesi a caso.
Tutto ciò ovviamente sempre che si decida di fare coi pesi e non lineare o altro

**Comment by NNazem** [comment]
Il problema è: come lo valutiamo? Non abbiamo un test data, non sappiamo chi  è realmente più famoso

**Comment by semroncoroni02** [comment]
> Sam non è che ogni risposta che ti do è per offenderti o per criticarti Ahahahaha, ho semplicemente detto in entrambi i casi andrebbe bene, l'importante è trovare il ranking migliore: se questo poi sia con o senza pesi lo capiremo solo con qualche test. Il numero di citazioni su wikipedia dovrebbe essere riferimenti ai link che ho messo, poi se intendi proprio citazioni senza link (che dubito vi siano, ma non ne sono sicuro) allora non so. Per le visualizzazioni dipende, per l'appunto Romolo ha tante citazioni ma poche visualizzazioni, il problema è che wikipedia non fornisce visualizzazioni totali ma soltanto negli ultimi 60 giorni

Nono, come citazioni intendevo il riferimento ai link che hai già fatto tu.
Non saprei, secondo me ognuno potrebbe mettere giù una scaletta in ordine di importanza e un commento sul perché secondo lui è quello l'orine più corretto per importanza.
Così facendo secondo me riusciamo a tirare fuori una scaletta generale , per quanto riguarda il commento invece credo possa essere utile sia a noi ma sopratutto al prof che così capisce che dietro c'è stato un determinato lavoro e non a abbiamo messo pesi a caso.
Tutto ciò ovviamente sempre che si decida di fare coi pesi e non lineare o altro

**Comment by semroncoroni02** [comment]
> Il problema è: come lo valutiamo? Non abbiamo un test data, non sappiamo chi è realmente più famoso

Ah intendi il fatto che non avendo un set di riferimento potremmo andare a determinare che quel Babbage di Leonardo Da Vinci potrebbe essere meno famoso di Rita LeviMontalcini nonostante invece probabilmente sia effettivamente più famoso?

**Comment by semroncoroni02** [comment]
Ho pensato che una ricerca comparando i vari personaggi su Google trends potesse essere utile ed effettivamente secondo me può esserlo siccome permette di confrontare i vari soggetti in base a differenti categorie, è inoltre possibile scegliere l'intervallo di tempo.
(Unica pecca è che è possibile confrontare solo 5 personaggi)

![image](https://user-images.githubusercontent.com/129330816/229312075-dfba9516-1cfa-4fc0-8128-6cb0009dff49.png)
![image](https://user-images.githubusercontent.com/129330816/229312111-546dd17f-2953-4ce5-b9e3-d9d655b66460.png)

**Comment by NNazem** [comment]
non avrei idea di come inserirlo in un csv però

**Comment by semroncoroni02** [comment]
> non avrei idea di come inserirlo in un csv però

https://raw.githubusercontent.com/TheNoobRoxas/bigData/main/Score_Ranking_TODO/PersonaggiFamosiGoogleTrends_1.csv
Non ho ben capito però se i numeri si riferiscono esattamente al numero di ricerche effettuate oppure è una percentuale oppure altro ahahah
Potremmo prendere il dato generale dai vari csv e poi inserire nel nostro un solo valore rappresentativo (tipo: numero ricerche ultimi 10 anni)

**Comment by NNazem** [comment]
è una misura relativa della popolarità della parola. inoltre se con il confronto il numero varia rispetto a quelle prese singolarmente, non possiamo usarlo per via del limite massimo di 5, dovremmo prendere i dati presi singolarmente

**Comment by NNazem** [comment]
https://medium.com/analytics-vidhya/compare-more-than-5-keywords-in-google-trends-search-using-pytrends-3462d6b5ad62
Questo è l'unico modo per usare google trends, i dati se presi singolarmente non sono direttamente confrontabili in quanto ci dicono soltanto l'andamento dell'interesse per una parola chiave in un dato momento, basato però sull'interesse passato: se Rita passa da 100 ricerche a 1000 avrà un valore altissimo, ma non significa che sia più alto di Dante che magari quel giorno ha avuto 50 mila ricerche, ma sotto la sua media. Dobbiamo per forza fare confronti bypassando il limite

**Comment by semroncoroni02** [comment]
Sono d'accordo sul fatto che ci indichino l'interesse in un determinato momento.
Ma secondo me è tutto rapportato, nel senso che se un giorno la Rita ha 1000 ricerche la sua media si alzerà, ma a confronto di dante l'impennata si noterà ovviamente meno siccome lui avrà una media molto più alta della rita durante tutto l'anno...
Il valore massimo della Rita potrebbe essere molto inferiore al valore massimo di Dante

Il totale delle ricerche della rita è pari a circa 550, mentre per dante siamo sui 4000
Il che ci dice che dante ha una media annua molto alta rispetto alla Rita che magari ha solo avuto un picco il giorno che si è tagliata i capelli e le vecchiette di quartiere sono andate a cercare il suo nuovo taglio
